### ISSUE TITLE
For invalid JSONs the Generate button replaces the user's text with the default one

### ISSUE THREAD

**Issue by taniapil** [arcanoid/multi-cool#8]
When you try to beautify an invalid json, the user's text is replaced by the sample/default text. Thus, the user loses any changes he may have made.
It would be nice and useful to keep the user's text and maybe add a "Clear" button, in case the user wants to clear the box.

**Comment by arcanoid** [comment]
For now it will keep the submitted text. In case "clear" button makes sense in the future, let's re-evaluate.
